// src/pro_hackathon-react-frontend/src/pages/Edit.jsx
import { useState } from "react";

const Edit = ({ riwayat, idx, user, onClose, onCloseDetail, refresh, onUpdated, setMessage, setSuccess }) => {
    const [gejala, setGejala] = useState(riwayat.gejala);
    const [tanggalMulai, setTanggalMulai] = useState(
        new Date(Number(riwayat.tanggal_mulai) / 1_000_000).toISOString().split("T")[0]
    );
    const [tanggalSembuh, setTanggalSembuh] = useState(
        riwayat.tanggal_sembuh != 0
            ? new Date(Number(riwayat.tanggal_sembuh) / 1_000_000).toISOString().split("T")[0]
            : ""
    );
    const [penyakit, setPenyakit] = useState(riwayat.penyakit?.[0] || "");
    const [catatanDokter, setCatatanDokter] = useState(riwayat.catatan_dokter?.[0] || "");

    const handleSubmit = async (e) => {
        e.preventDefault();
        try {
            const principal = user.authClient.getIdentity().getPrincipal();

            const mulaiNano = BigInt(new Date(tanggalMulai).getTime()) * 1_000_000n;
            const sembuhNano = tanggalSembuh
                ? BigInt(new Date(tanggalSembuh).getTime()) * 1_000_000n
                : null;

            const res = await user.actor.updateRiwayat(
                principal,
                idx,
                penyakit.length > 0 ? [penyakit] : [],
                gejala,
                mulaiNano,
                sembuhNano ? [sembuhNano] : [],
                catatanDokter.length > 0 ? [catatanDokter] : []
            );

            if (res) {
                refresh();
                onCloseDetail();
                onClose();
                if (onUpdated) {
                    onUpdated({
                        ...riwayat,
                        penyakit,
                        gejala,
                        tanggal_mulai: mulaiNano,
                        tanggal_sembuh: sembuhNano || null,
                        catatan_dokter: catatanDokter,
                    });
                }

                setMessage("Riwayat berhasil diperbarui!");
                setSuccess(true);
            }
        } catch (err) {
            setMessage("Terjadi kesalahan saat memperbarui!");
            setSuccess(false);
        }
    };

    return (
        // Latar belakang modal (backdrop) tetap sama
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-gray-900/60 backdrop-blur-sm p-4">

            {/* 1. Container Card disesuaikan agar mirip dengan halaman Create */}
            <div className="w-full max-w-2xl bg-white p-8 rounded-2xl shadow-lg border border-gray-100">

                {/* 2. Header ditambahkan untuk konsistensi */}
                <div className="text-center mb-8">
                    <h1 className="text-xl sm:text-3xl font-semibold text-red-600 mb-1">
                        Edit Riwayat Kesehatan
                    </h1>
                    <p className="text-gray-500 text-base">
                        Perbarui detail di bawah ini untuk mengubah catatan.
                    </p>
                </div>

                {/* Form dengan styling yang diperbarui */}
                <form onSubmit={handleSubmit} className="space-y-4">

                    {/* 3. Urutan dan styling field disesuaikan */}
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <div>
                            <label htmlFor="tanggalMulai" className="block text-sm font-medium text-gray-700 mb-1">
                                Tanggal Mulai Sakit <span className="text-red-500">*</span>
                            </label>
                            <input
                                id="tanggalMulai"
                                type="date"
                                value={tanggalMulai}
                                onChange={(e) => setTanggalMulai(e.target.value)}
                                required
                                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-red-500 focus:border-red-500 transition text-base"
                            />
                        </div>
                        <div>
                            <label htmlFor="tanggalSembuh" className="block text-sm font-medium text-gray-700 mb-1">
                                Tanggal Sembuh (Opsional)
                            </label>
                            <input
                                id="tanggalSembuh"
                                type="date"
                                value={tanggalSembuh ?? ""}
                                onChange={(e) => setTanggalSembuh(e.target.value)}
                                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-red-500 focus:border-red-500 transition text-base"
                            />
                        </div>
                    </div>

                    <div>
                        <label htmlFor="gejala" className="block text-sm font-medium text-gray-700 mb-1">
                            Gejala yang Dirasakan <span className="text-red-500">*</span>
                        </label>
                        <textarea
                            id="gejala"
                            value={gejala}
                            onChange={(e) => setGejala(e.target.value)}
                            rows="4"
                            required
                            className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-red-500 focus:border-red-500 transition text-base"
                            placeholder="Contoh: Demam tinggi, sakit kepala, dan batuk kering..."
                        />
                    </div>

                    <div>
                        <label htmlFor="penyakit" className="block text-sm font-medium text-gray-700 mb-1">
                            Diagnosis Penyakit (Opsional)
                        </label>
                        <input
                            id="penyakit"
                            type="text"
                            value={penyakit}
                            onChange={(e) => setPenyakit(e.target.value)}
                            className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-red-500 focus:border-red-500 transition text-base"
                            placeholder="Contoh: Influenza Tipe A"
                        />
                    </div>

                    <div>
                        <label htmlFor="catatanDokter" className="block text-sm font-medium text-gray-700 mb-1">
                            Catatan Dokter (Opsional)
                        </label>
                        <textarea
                            id="catatanDokter"
                            value={catatanDokter}
                            onChange={(e) => setCatatanDokter(e.target.value)}
                            rows="3"
                            className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-red-500 focus:border-red-500 transition text-base"
                            placeholder="Catatan tambahan dari dokter..."
                        />
                    </div>

                    {/* 4. Tombol Aksi diperbarui dengan gaya yang konsisten */}
                    <div className="flex justify-end gap-4 pt-4">
                        <button
                            type="button"
                            onClick={onClose}
                            className="bg-white text-base text-gray-700 border border-gray-300 font-semibold py-2 px-5 rounded-lg hover:bg-gray-100 transition duration-300 ease-in-out cursor-pointer"
                        >
                            Batal
                        </button>
                        <button
                            type="submit"
                            className="px-5 py-2.5 bg-red-500 text-white font-semibold rounded-lg hover:bg-red-600 transition text-base cursor-pointer"
                        >
                            Simpan Perubahan
                        </button>
                    </div>
                </form>
            </div>
        </div>
    );
};

export default Edit;

// src/pro_hackathon_frontend/src/views/Edit.vue
<script setup>
import { ref, onMounted } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { pro_hackathon_backend } from 'declarations/pro_hackathon_backend/index';

const route = useRoute();
const router = useRouter();
const record = ref(null);
const isLoading = ref(true);
const message = ref('');

function toInputDate(timestamp) {
    if (!timestamp) return '';
    const date = new Date(Number(timestamp) / 1_000_000);
    return date.toISOString().split('T')[0];
}

onMounted(async () => {
    try {
        const recordId = BigInt(route.params.id);
        const result = await pro_hackathon_backend.getRecordById(recordId);
        if (result.length > 0) {
            const fetchedRecord = result[0];
            record.value = {
                ...fetchedRecord,
                startDate: toInputDate(fetchedRecord.startDate),
                endDate: fetchedRecord.endDate.length > 0 ? toInputDate(fetchedRecord.endDate[0]) : '',
                diagnosis: fetchedRecord.diagnosis[0] || ''
            };
        } else {
            throw new Error("Catatan tidak ditemukan.");
        }
    } catch (error) {
        message.value = `Error: ${error.message}`;
    } finally {
        isLoading.value = false;
    }
});

async function handleUpdateRecord() {
    isLoading.value = true;
    message.value = '';
    try {
        const recordId = BigInt(route.params.id);

        // --- PERBAIKAN DI SINI ---
        // Kalikan dengan 1_000_000 untuk mengubah dari milidetik ke nanodetik
        const startDateInt = BigInt(Date.parse(record.value.startDate) * 1_000_000);

        const endDateOpt = record.value.endDate
            ? [BigInt(Date.parse(record.value.endDate) * 1_000_000)]
            : [];

        const diagnosisOpt = record.value.diagnosis ? [record.value.diagnosis] : [];

        const result = await pro_hackathon_backend.updateRecord(
            recordId,
            startDateInt,
            endDateOpt,
            record.value.symptoms,
            diagnosisOpt
        );

        if (result.ok) {
            router.push(`/detail/${recordId}?status=updated`);
        } else {
            throw new Error(result.err);
        }

    } catch (error) {
        message.value = `Error: ${error.message}`;
    } finally {
        isLoading.value = false;
    }
}
</script>

<template>
    <div class="relative isolate bg-white">

        <div class="absolute inset-x-0 -top-40 -z-10 transform-gpu overflow-hidden blur-3xl sm:-top-80"
            aria-hidden="true">
            <div class="relative left-[calc(50%-11rem)] aspect-[1155/678] w-[36.125rem] -translate-x-1/2 rotate-[30deg] bg-gradient-to-tr from-[#ff8080] to-[#f55050] opacity-20 sm:left-[calc(50%-30rem)] sm:w-[72.1875rem]"
                style="clip-path: polygon(74.1% 44.1%, 100% 61.6%, 97.5% 26.9%, 85.5% 0.1%, 80.7% 2%, 72.5% 32.5%, 60.2% 62.4%, 52.4% 68.1%, 47.5% 58.3%, 45.2% 34.5%, 27.5% 76.7%, 0.1% 64.9%, 17.9% 100%, 27.6% 76.8%, 76.1% 97.7%, 74.1% 44.1%)">
            </div>
        </div>
        <div class="absolute inset-x-0 top-[calc(100%-13rem)] -z-10 transform-gpu overflow-hidden blur-3xl sm:top-[calc(100%-30rem)]"
            aria-hidden="true">
            <div class="relative left-[calc(50%+3rem)] aspect-[1155/678] w-[36.125rem] -translate-x-1/2 bg-gradient-to-tr from-[#f87171] to-[#dc2626] opacity-20 sm:left-[calc(50%+36rem)] sm:w-[72.1875rem]"
                style="clip-path: polygon(74.1% 44.1%, 100% 61.6%, 97.5% 26.9%, 85.5% 0.1%, 80.7% 2%, 72.5% 32.5%, 60.2% 62.4%, 52.4% 68.1%, 47.5% 58.3%, 45.2% 34.5%, 27.5% 76.7%, 0.1% 64.9%, 17.9% 100%, 27.6% 76.8%, 76.1% 97.7%, 74.1% 44.1%)">
            </div>
        </div>
        <main class="flex-grow flex items-center justify-center z-10 py-12">
            <div class="container mx-auto px-4">

                <div v-if="isLoading" class="text-center">Memuat data...</div>
                <div v-else-if="!record" class="text-center text-red-500">{{ message }}</div>

                <div v-else
                    class="max-w-2xl mx-auto bg-white/80 backdrop-blur-sm p-8 rounded-2xl shadow-lg border border-gray-100">
                    <div class="text-center mb-8">
                        <h1 class="text-xl sm:text-2xl font-semibold text-red-600 mb-1">Edit Catatan Kesehatan</h1>
                        <p class="text-gray-500 text-sm">Perbarui detail catatan</p>
                    </div>
                    <form @submit.prevent="handleUpdateRecord" class="space-y-6 text-left">
                        <div>
                            <label for="startDate" class="block text-sm font-medium text-gray-700 mb-1">Tanggal Mulai
                                Sakit <span class="text-red-500">*</span></label>
                            <input v-model="record.startDate" type="date" id="startDate"
                                class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-red-500 focus:border-red-500 transition">
                        </div>
                        <div>
                            <label for="endDate" class="block text-sm font-medium text-gray-700 mb-1">Tanggal Sembuh
                                (Opsional)</label>
                            <input v-model="record.endDate" type="date" id="endDate"
                                class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-red-500 focus:border-red-500 transition">
                        </div>
                        <div>
                            <label for="symptoms" class="block text-sm font-medium text-gray-700 mb-1">Gejala yang
                                Dirasakan <span class="text-red-500">*</span></label>
                            <textarea v-model="record.symptoms" id="symptoms" rows="4"
                                class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-red-500 focus:border-red-500 transition"></textarea>
                        </div>
                        <div>
                            <label for="diagnosis" class="block text-sm font-medium text-gray-700 mb-1">Diagnosis
                                Penyakit (Opsional)</label>
                            <input v-model="record.diagnosis" type="text" id="diagnosis"
                                class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-red-500 focus:border-red-500 transition">
                        </div>
                        <div class="pt-2">
                            <button type="submit" :disabled="isLoading"
                                class="w-full bg-red-500 text-white font-semibold py-3 px-6 rounded-lg hover:bg-red-600 transition disabled:bg-red-300">
                                {{ isLoading ? 'Menyimpan...' : 'Simpan Perubahan' }}
                            </button>
                        </div>
                    </form>
                    <div v-if="message" class="mt-6 text-center text-sm p-3 rounded-lg"
                        :class="{ 'bg-green-50 text-green-700': message.includes('Sukses'), 'bg-red-50 text-red-700': message.includes('Error') }">
                        {{ message }}
                    </div>
                </div>
            </div>
        </main>

        <router-link to="/dashboard"
            class="fixed bottom-6 right-6 h-14 w-14 bg-red-500 rounded-full flex items-center justify-center text-white shadow-lg hover:bg-red-600 transition-transform hover:scale-110">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-7 w-7" fill="none" viewBox="0 0 24 24"
                stroke="currentColor" stroke-width="2">
                <path stroke-linecap="round" stroke-linejoin="round"
                    d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" />
            </svg>
        </router-link>
    </div>
</template>
